"""Submission format inspection, creation, and validation utilities.

The leaderboard submission format is treated as data. When a sample submission
is available, its archive member paths become the authoritative contract. When
no sample exists, the module can infer a provisional PNG-mask layout from
``DataInfo`` generated by :mod:`src.data.inspect_sufe`.
"""

from __future__ import annotations

import argparse
import io
import json
import re
import zipfile
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass, field
from pathlib import Path, PurePosixPath
from typing import Any, Iterable

import numpy as np
from PIL import Image


MASK_EXTENSIONS = {".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff", ".webp"}
ZIP_COMPRESSION = zipfile.ZIP_DEFLATED


@dataclass(slots=True)
class FormatSpec:
    """Submission mask-path and mask-encoding contract."""

    relative_mask_path_pattern: str
    mask_extension: str
    mask_encoding: str
    object_id_encoding_rule: str
    expected_videos: list[str]
    expected_frame_count_per_video: dict[str, int]
    image_size_per_video: dict[str, list[int]]
    not_verified_by_sample: bool
    expected_masks: list[dict[str, Any]] = field(default_factory=list)
    sample_relative_paths: list[str] = field(default_factory=list)
    format_source: str = "sample_submission"
    notes: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-serializable representation."""

        return asdict(self)

    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> "FormatSpec":
        """Create a format spec from a JSON dictionary."""

        return cls(
            relative_mask_path_pattern=payload.get("relative_mask_path_pattern", "{video_id}/{frame_stem}.png"),
            mask_extension=payload.get("mask_extension", ".png"),
            mask_encoding=payload.get("mask_encoding", "unknown"),
            object_id_encoding_rule=payload.get("object_id_encoding_rule", "unknown"),
            expected_videos=list(payload.get("expected_videos", [])),
            expected_frame_count_per_video=dict(payload.get("expected_frame_count_per_video", {})),
            image_size_per_video=dict(payload.get("image_size_per_video", {})),
            not_verified_by_sample=bool(payload.get("not_verified_by_sample", True)),
            expected_masks=list(payload.get("expected_masks", [])),
            sample_relative_paths=list(payload.get("sample_relative_paths", [])),
            format_source=payload.get("format_source", "unknown"),
            notes=list(payload.get("notes", [])),
        )


def _load_format_spec(format_spec: FormatSpec | dict[str, Any] | str | Path) -> FormatSpec:
    """Normalize a format spec input to a ``FormatSpec`` object."""

    if isinstance(format_spec, FormatSpec):
        return format_spec
    if isinstance(format_spec, dict):
        return FormatSpec.from_dict(format_spec)
    payload = json.loads(Path(format_spec).read_text(encoding="utf-8"))
    return FormatSpec.from_dict(payload)


def save_format_spec(format_spec: FormatSpec, output: str | Path) -> None:
    """Write a format spec to JSON."""

    output_path = Path(output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(format_spec.to_dict(), indent=2, ensure_ascii=True), encoding="utf-8")


def _valid_archive_member(name: str) -> bool:
    """Return whether a zip member is a normal relative file path."""

    pure = PurePosixPath(name)
    if name.endswith("/"):
        return False
    if name.startswith("/") or any(part in {"", ".", ".."} for part in pure.parts):
        return False
    if pure.parts and pure.parts[0] == "__MACOSX":
        return False
    if any(part.startswith("._") for part in pure.parts):
        return False
    return True


def _natural_key(text: str) -> list[int | str]:
    """Sort text with embedded numbers in numeric order."""

    return [int(part) if part.isdigit() else part.lower() for part in re.split(r"(\d+)", text)]


def _frame_index_from_stem(stem: str, fallback: int) -> int:
    """Extract an integer frame index from a stem or use fallback order."""

    if stem.isdigit():
        return int(stem)
    numbers = re.findall(r"\d+", stem)
    return int(numbers[-1]) if numbers else fallback


def _mask_encoding_from_array(array: np.ndarray) -> tuple[str, list[int]]:
    """Infer binary/indexed mask style from unique pixel values."""

    if array.ndim == 3:
        array = np.any(array[..., :3] > 0, axis=-1).astype(np.uint8)
    unique_values = sorted(int(value) for value in np.unique(array).tolist())
    positive_values = [value for value in unique_values if value > 0]
    if set(unique_values).issubset({0, 1, 255}) and len(positive_values) <= 2:
        return "binary_png", unique_values
    return "indexed_png", unique_values


def _video_id_from_mask_path(relative_path: str) -> str:
    """Infer video id from a sample mask path."""

    pure = PurePosixPath(relative_path)
    if len(pure.parts) >= 2:
        return pure.parent.name
    return "root"


def _pattern_from_paths(paths: list[str]) -> str:
    """Infer a readable mask path pattern from sample member names."""

    if not paths:
        return "{video_id}/{frame_stem}.png"
    first = PurePosixPath(paths[0])
    video_id = _video_id_from_mask_path(paths[0])
    frame_stem = first.stem
    pattern = first.as_posix()
    pattern = pattern.replace(video_id, "{video_id}", 1)
    suffix = first.suffix
    if suffix:
        pattern = re.sub(rf"{re.escape(frame_stem)}{re.escape(suffix)}$", "{frame_stem}" + suffix, pattern)
    return pattern


def _iter_sample_images(sample_zip_or_dir: str | Path) -> list[tuple[str, bytes]]:
    """Return sample image entries as ``(relative_path, bytes)`` pairs."""

    sample_path = Path(sample_zip_or_dir).expanduser()
    if not sample_path.exists():
        raise FileNotFoundError(f"Sample submission does not exist: {sample_path}")

    entries: list[tuple[str, bytes]] = []
    if sample_path.is_file() and zipfile.is_zipfile(sample_path):
        with zipfile.ZipFile(sample_path, "r") as zf:
            for info in sorted(zf.infolist(), key=lambda item: _natural_key(item.filename)):
                if not _valid_archive_member(info.filename):
                    continue
                if PurePosixPath(info.filename).suffix.lower() not in MASK_EXTENSIONS:
                    continue
                entries.append((PurePosixPath(info.filename).as_posix(), zf.read(info)))
    elif sample_path.is_dir():
        for path in sorted((p for p in sample_path.rglob("*") if p.is_file()), key=lambda p: _natural_key(p.as_posix())):
            rel = path.relative_to(sample_path).as_posix()
            if not _valid_archive_member(rel):
                continue
            if path.suffix.lower() not in MASK_EXTENSIONS:
                continue
            entries.append((rel, path.read_bytes()))
    else:
        raise ValueError(f"Sample path must be a zip file or directory: {sample_path}")

    if not entries:
        raise ValueError(f"No mask image files found in sample submission: {sample_path}")
    return entries


def inspect_sample_submission(sample_zip_or_dir: str | Path) -> FormatSpec:
    """Inspect a sample submission archive or directory.

    Args:
        sample_zip_or_dir: Path to ``sample_submission.zip`` or an extracted
            sample submission directory.

    Returns:
        A ``FormatSpec`` whose expected paths match the sample exactly.
    """

    entries = _iter_sample_images(sample_zip_or_dir)
    expected_masks: list[dict[str, Any]] = []
    expected_videos: set[str] = set()
    counts: Counter[str] = Counter()
    sizes: dict[str, list[int]] = {}
    encodings: Counter[str] = Counter()
    suffixes: Counter[str] = Counter()

    for order, (relative_path, data) in enumerate(entries):
        pure = PurePosixPath(relative_path)
        video_id = _video_id_from_mask_path(relative_path)
        expected_videos.add(video_id)
        counts[video_id] += 1
        suffixes[pure.suffix.lower()] += 1
        with Image.open(io.BytesIO(data)) as image:
            array = np.asarray(image)
            width, height = image.size
        sizes.setdefault(video_id, [width, height])
        encoding, unique_values = _mask_encoding_from_array(array)
        encodings[encoding] += 1
        expected_masks.append(
            {
                "relative_path": pure.as_posix(),
                "video_id": video_id,
                "frame_stem": pure.stem,
                "frame_index": _frame_index_from_stem(pure.stem, order),
                "width": width,
                "height": height,
                "unique_values_sample": unique_values[:256],
            }
        )

    if encodings.get("indexed_png"):
        mask_encoding = "indexed_png"
        object_rule = "pixel_value_object_id"
    elif encodings.get("binary_png"):
        mask_encoding = "binary_png"
        object_rule = "foreground_is_1_or_255"
    else:
        mask_encoding = "unknown"
        object_rule = "unknown"

    mask_extension = suffixes.most_common(1)[0][0]
    sorted_paths = [entry[0] for entry in entries]
    return FormatSpec(
        relative_mask_path_pattern=_pattern_from_paths(sorted_paths),
        mask_extension=mask_extension,
        mask_encoding=mask_encoding,
        object_id_encoding_rule=object_rule,
        expected_videos=sorted(expected_videos, key=str.lower),
        expected_frame_count_per_video=dict(sorted(counts.items(), key=lambda item: item[0].lower())),
        image_size_per_video=dict(sorted(sizes.items(), key=lambda item: item[0].lower())),
        not_verified_by_sample=False,
        expected_masks=expected_masks,
        sample_relative_paths=sorted_paths,
        format_source=str(sample_zip_or_dir),
    )


def _data_info_dict(data_info: dict[str, Any] | str | Path) -> dict[str, Any]:
    """Normalize data-info input to a dictionary."""

    if isinstance(data_info, dict):
        return data_info
    return json.loads(Path(data_info).read_text(encoding="utf-8"))


def _has_annotations_structure(data_info: dict[str, Any]) -> bool:
    """Return whether the inspected data appears to use an Annotations tree."""

    scan = data_info.get("scan", {})
    top_level = {str(name).lower() for name in scan.get("top_level_entries", [])}
    if "annotations" in top_level:
        return True
    for video in data_info.get("videos", []):
        for prompt in video.get("prompts", []):
            parts = PurePosixPath(prompt.get("relative_path", "")).parts
            if parts and parts[0].lower() == "annotations":
                return True
    return False


def infer_provisional_format(data_info: dict[str, Any] | str | Path) -> FormatSpec:
    """Infer a provisional submission format when no sample submission exists."""

    info = _data_info_dict(data_info)
    use_annotations = _has_annotations_structure(info)
    pattern = "Annotations/{video_id}/{frame_stem}.png" if use_annotations else "{video_id}/{frame_stem}.png"
    prompt_format = info.get("prompt_format", {})
    mask_counts = prompt_format.get("mask_encoding_counts", {})

    if mask_counts.get("indexed_png"):
        mask_encoding = "indexed_png"
        object_rule = "pixel_value_object_id"
    else:
        mask_encoding = "binary_png"
        object_rule = "foreground_is_1_or_255"

    expected_masks: list[dict[str, Any]] = []
    expected_videos: list[str] = []
    counts: dict[str, int] = {}
    sizes: dict[str, list[int]] = {}

    for video in sorted(info.get("videos", []), key=lambda item: str(item.get("video_id", "")).lower()):
        video_id = str(video.get("video_id"))
        if not video_id:
            continue
        expected_videos.append(video_id)
        width = video.get("width")
        height = video.get("height")
        if width and height:
            sizes[video_id] = [int(width), int(height)]
        frames = video.get("frames", [])
        if frames:
            for order, frame in enumerate(sorted(frames, key=lambda item: _natural_key(str(item.get("relative_path", ""))))):
                frame_stem = str(frame.get("frame_stem") or PurePosixPath(str(frame.get("relative_path", ""))).stem)
                relative_path = pattern.format(video_id=video_id, frame_stem=frame_stem)
                expected_masks.append(
                    {
                        "relative_path": relative_path,
                        "video_id": video_id,
                        "frame_stem": frame_stem,
                        "frame_index": int(frame.get("frame_index", order)),
                        "width": int(frame.get("width") or width or 0),
                        "height": int(frame.get("height") or height or 0),
                    }
                )
            counts[video_id] = len(frames)
        else:
            frame_count = int(video.get("frame_count") or 0)
            pad = max(5, len(str(max(frame_count - 1, 0))))
            for frame_index in range(frame_count):
                frame_stem = f"{frame_index:0{pad}d}"
                relative_path = pattern.format(video_id=video_id, frame_stem=frame_stem)
                expected_masks.append(
                    {
                        "relative_path": relative_path,
                        "video_id": video_id,
                        "frame_stem": frame_stem,
                        "frame_index": frame_index,
                        "width": int(width or 0),
                        "height": int(height or 0),
                    }
                )
            counts[video_id] = frame_count

    return FormatSpec(
        relative_mask_path_pattern=pattern,
        mask_extension=".png",
        mask_encoding=mask_encoding,
        object_id_encoding_rule=object_rule,
        expected_videos=expected_videos,
        expected_frame_count_per_video=counts,
        image_size_per_video=sizes,
        not_verified_by_sample=True,
        expected_masks=expected_masks,
        sample_relative_paths=[mask["relative_path"] for mask in expected_masks],
        format_source="provisional_from_data_info",
        notes=["not_verified_by_sample"],
    )


def _candidate_prediction_paths(pred_root: Path, mask: dict[str, Any], extension: str) -> list[Path]:
    """Return plausible source mask paths for one expected output mask."""

    rel = PurePosixPath(mask["relative_path"])
    video_id = str(mask["video_id"])
    frame_stem = str(mask["frame_stem"])
    filename = frame_stem + extension
    candidates = [
        pred_root / Path(rel.as_posix()),
        pred_root / video_id / filename,
        pred_root / video_id / f"{frame_stem}.png",
        pred_root / "Annotations" / video_id / filename,
        pred_root / "Annotations" / video_id / f"{frame_stem}.png",
        pred_root / "masks" / video_id / filename,
        pred_root / "masks" / video_id / f"{frame_stem}.png",
    ]
    for suffix in MASK_EXTENSIONS:
        candidates.append(pred_root / video_id / f"{frame_stem}{suffix}")
        candidates.append(pred_root / "Annotations" / video_id / f"{frame_stem}{suffix}")
    seen: set[Path] = set()
    unique: list[Path] = []
    for candidate in candidates:
        if candidate not in seen:
            seen.add(candidate)
            unique.append(candidate)
    return unique


def _read_prediction_bytes(source_path: Path, dest_extension: str) -> bytes:
    """Read or transcode prediction bytes for the destination extension."""

    if source_path.suffix.lower() == dest_extension.lower():
        return source_path.read_bytes()
    with Image.open(source_path) as image:
        output = io.BytesIO()
        if dest_extension.lower() == ".png":
            image.save(output, format="PNG")
        elif dest_extension.lower() in {".jpg", ".jpeg"}:
            image.convert("L").save(output, format="JPEG")
        else:
            image.save(output)
        return output.getvalue()


def make_submission(pred_root: str | Path, output_zip: str | Path, format_spec: FormatSpec | dict[str, Any] | str | Path) -> None:
    """Create a submission zip from a prediction mask root.

    The archive member names are taken from ``format_spec.expected_masks``.
    No extra top-level directory is added.
    """

    spec = _load_format_spec(format_spec)
    pred_root_path = Path(pred_root).expanduser().resolve()
    if not pred_root_path.exists():
        raise FileNotFoundError(f"Prediction root does not exist: {pred_root_path}")

    output_path = Path(output_zip)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    missing: list[str] = []
    with zipfile.ZipFile(output_path, "w", compression=ZIP_COMPRESSION) as zf:
        for mask in sorted(spec.expected_masks, key=lambda item: _natural_key(item["relative_path"])):
            source_path = next((path for path in _candidate_prediction_paths(pred_root_path, mask, spec.mask_extension) if path.exists()), None)
            if source_path is None:
                missing.append(mask["relative_path"])
                continue
            zf.writestr(mask["relative_path"], _read_prediction_bytes(source_path, spec.mask_extension))

    if missing:
        output_path.unlink(missing_ok=True)
        raise FileNotFoundError(f"Missing {len(missing)} prediction masks. First missing paths: {missing[:10]}")


def _zip_entries(output_zip: str | Path) -> tuple[dict[str, bytes], dict[str, bytes], list[str]]:
    """Read normal file entries, image entries, and invalid member names."""

    output_path = Path(output_zip)
    if not output_path.exists():
        raise FileNotFoundError(f"Submission zip does not exist: {output_path}")
    if not zipfile.is_zipfile(output_path):
        raise ValueError(f"Not a zip file: {output_path}")

    all_entries: dict[str, bytes] = {}
    image_entries: dict[str, bytes] = {}
    invalid_names: list[str] = []
    with zipfile.ZipFile(output_path, "r") as zf:
        for info in zf.infolist():
            if not _valid_archive_member(info.filename):
                if not info.filename.endswith("/"):
                    invalid_names.append(info.filename)
                continue
            name = PurePosixPath(info.filename).as_posix()
            data = zf.read(info)
            all_entries[name] = data
            suffix = PurePosixPath(info.filename).suffix.lower()
            if suffix in MASK_EXTENSIONS:
                image_entries[name] = data
    return all_entries, image_entries, invalid_names


def _known_object_ids_by_video(data_info: dict[str, Any]) -> dict[str, set[int]]:
    """Extract object ids from detected prompts by video."""

    known: dict[str, set[int]] = defaultdict(set)
    for video in data_info.get("videos", []):
        video_id = str(video.get("video_id", ""))
        for prompt in video.get("prompts", []):
            for object_id in prompt.get("object_ids", []) or []:
                if int(object_id) > 0:
                    known[video_id].add(int(object_id))
    return known


def _validate_object_ids(
    array: np.ndarray,
    video_id: str,
    spec: FormatSpec,
    known_ids: dict[str, set[int]],
    errors: list[str],
    warnings: list[str],
    relative_path: str,
) -> None:
    """Validate mask object id values against the format contract."""

    if array.ndim == 3:
        array = np.any(array[..., :3] > 0, axis=-1).astype(np.uint8)
    unique_values = sorted(int(value) for value in np.unique(array).tolist())
    positive_values = [value for value in unique_values if value > 0]

    if spec.mask_encoding == "binary_png" or spec.object_id_encoding_rule == "foreground_is_1_or_255":
        illegal = [value for value in unique_values if value not in {0, 1, 255}]
        if illegal:
            errors.append(f"{relative_path}: binary mask contains illegal values {illegal[:20]}")
        return

    if spec.mask_encoding == "indexed_png" or spec.object_id_encoding_rule == "pixel_value_object_id":
        if any(value < 0 or value > 255 for value in unique_values):
            errors.append(f"{relative_path}: indexed PNG values must be in [0, 255]")
        legal = known_ids.get(video_id, set())
        if legal:
            illegal = [value for value in positive_values if value not in legal]
            if illegal:
                errors.append(f"{relative_path}: object ids {illegal[:20]} are not in known prompt ids {sorted(legal)}")
        else:
            warnings.append(f"{relative_path}: no prompt object ids available; indexed ids were range-checked only")
        return

    warnings.append(f"{relative_path}: mask encoding is unknown; object-id legality was not fully checked")


def validate_submission_zip(
    output_zip: str | Path,
    format_spec: FormatSpec | dict[str, Any] | str | Path,
    data_info: dict[str, Any] | str | Path,
) -> dict[str, Any]:
    """Validate a submission zip against a format spec and dataset info."""

    spec = _load_format_spec(format_spec)
    info = _data_info_dict(data_info)
    all_entries, entries, invalid_names = _zip_entries(output_zip)
    expected_paths = {mask["relative_path"] for mask in spec.expected_masks}
    actual_paths = set(entries)
    all_paths = set(all_entries)
    errors: list[str] = []
    warnings: list[str] = []

    if invalid_names:
        errors.append(f"Found {len(invalid_names)} invalid archive member names. First: {invalid_names[:10]}")

    missing = sorted(expected_paths - all_paths, key=_natural_key)
    extra = sorted(all_paths - expected_paths, key=_natural_key)
    if missing:
        errors.append(f"Missing {len(missing)} expected masks. First: {missing[:10]}")
    if extra:
        errors.append(f"Found {len(extra)} unexpected files. First: {extra[:10]}")

    non_image_expected = sorted((expected_paths & all_paths) - actual_paths, key=_natural_key)
    if non_image_expected:
        errors.append(f"Expected mask paths are not readable image entries. First: {non_image_expected[:10]}")

    for name in all_paths:
        if name.startswith("/") or ".." in PurePosixPath(name).parts:
            errors.append(f"{name}: invalid archive path")
        if PurePosixPath(name).suffix.lower() != spec.mask_extension.lower():
            errors.append(f"{name}: expected extension {spec.mask_extension}")

    expected_counts = Counter(mask["video_id"] for mask in spec.expected_masks)
    actual_counts = Counter(_video_id_from_mask_path(path) for path in actual_paths if path in expected_paths)
    for video_id, expected_count in spec.expected_frame_count_per_video.items():
        if expected_counts.get(video_id, 0) != expected_count:
            warnings.append(f"{video_id}: format spec expected count field {expected_count} differs from expected mask list {expected_counts.get(video_id, 0)}")
        if actual_counts.get(video_id, 0) != expected_counts.get(video_id, 0):
            errors.append(f"{video_id}: expected {expected_counts.get(video_id, 0)} masks, found {actual_counts.get(video_id, 0)}")

    known_ids = _known_object_ids_by_video(info)
    expected_by_path = {mask["relative_path"]: mask for mask in spec.expected_masks}
    for relative_path in sorted(actual_paths & expected_paths, key=_natural_key):
        mask = expected_by_path[relative_path]
        with Image.open(io.BytesIO(entries[relative_path])) as image:
            width, height = image.size
            array = np.asarray(image)
        expected_width = int(mask.get("width") or 0)
        expected_height = int(mask.get("height") or 0)
        if not expected_width or not expected_height:
            size = spec.image_size_per_video.get(str(mask["video_id"]))
            if size:
                expected_width, expected_height = int(size[0]), int(size[1])
        if expected_width and expected_height and (width != expected_width or height != expected_height):
            errors.append(f"{relative_path}: expected size {expected_width}x{expected_height}, got {width}x{height}")
        _validate_object_ids(array, str(mask["video_id"]), spec, known_ids, errors, warnings, relative_path)

    result = {
        "passed": not errors,
        "errors": errors,
        "warnings": warnings,
        "num_expected_masks": len(expected_paths),
        "num_actual_masks": len(actual_paths),
        "expected_videos": spec.expected_videos,
        "not_verified_by_sample": spec.not_verified_by_sample,
        "mask_encoding": spec.mask_encoding,
        "object_id_encoding_rule": spec.object_id_encoding_rule,
    }
    return result


def _build_arg_parser() -> argparse.ArgumentParser:
    """Build the command-line parser for submission utilities."""

    parser = argparse.ArgumentParser(description="Inspect, create, and validate SUFE submissions.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    inspect_parser = subparsers.add_parser("inspect-sample", help="Inspect sample submission zip or directory.")
    inspect_parser.add_argument("--sample", required=True, help="sample_submission.zip or extracted sample directory.")
    inspect_parser.add_argument("--output", required=True, help="Output format_spec.json path.")

    provisional_parser = subparsers.add_parser("infer-provisional", help="Infer provisional format from data_info.json.")
    provisional_parser.add_argument("--data-info", required=True, help="Input data_info.json path.")
    provisional_parser.add_argument("--output", required=True, help="Output format_spec.json path.")

    make_parser = subparsers.add_parser("make", help="Create submission.zip from prediction masks.")
    make_parser.add_argument("--pred-root", required=True, help="Prediction mask root.")
    make_parser.add_argument("--output-zip", required=True, help="Output submission.zip path.")
    make_parser.add_argument("--format-spec", required=True, help="format_spec.json path.")

    validate_parser = subparsers.add_parser("validate", help="Validate submission.zip.")
    validate_parser.add_argument("--output-zip", required=True, help="submission.zip path.")
    validate_parser.add_argument("--format-spec", required=True, help="format_spec.json path.")
    validate_parser.add_argument("--data-info", required=True, help="data_info.json path.")
    validate_parser.add_argument("--sanity-output", help="Optional sanity_check.json path.")
    return parser


def main(argv: list[str] | None = None) -> int:
    """CLI entrypoint for ``python -m src.data.submission``."""

    parser = _build_arg_parser()
    args = parser.parse_args(argv)

    if args.command == "inspect-sample":
        spec = inspect_sample_submission(args.sample)
        save_format_spec(spec, args.output)
        print(json.dumps(spec.to_dict(), indent=2, ensure_ascii=True))
        return 0

    if args.command == "infer-provisional":
        spec = infer_provisional_format(args.data_info)
        save_format_spec(spec, args.output)
        print(json.dumps(spec.to_dict(), indent=2, ensure_ascii=True))
        return 0

    if args.command == "make":
        make_submission(args.pred_root, args.output_zip, args.format_spec)
        print(f"Wrote {args.output_zip}")
        return 0

    if args.command == "validate":
        result = validate_submission_zip(args.output_zip, args.format_spec, args.data_info)
        if args.sanity_output:
            output_path = Path(args.sanity_output)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(json.dumps(result, indent=2, ensure_ascii=True), encoding="utf-8")
        print(json.dumps(result, indent=2, ensure_ascii=True))
        return 0 if result["passed"] else 1

    parser.error(f"Unknown command: {args.command}")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
